	#define TOKEN_INICIO 1
	#define TOKEN_FIN 2
	#define TOKEN_VECTOR 3
	#define TOKEN_ENTERO 4
	#define TOKEN_LOGICO 5
	#define TOKEN_SERGIO 6
	#define TOKEN_YAEL 7
	#define TOKEN_PAREDES 8
	#define TOKEN_CRUZ 9